### ISSUE TITLE
Budget Lines and Cost Breakdown Not Loading Properly

### ISSUE THREAD

**Issue by iMiiTH** [kanboard/plugin-budget#12]
Hello.

I'm using the latest version of Kanboard (v1.0.27), and just tried out the plugin, but when I click the Budget Lines or Cost Breakdown links, the pages appear like the images below:

<img width="337" alt="screenshot 2016-03-31 18 55 12" src="https://cloud.githubusercontent.com/assets/629266/14193366/1ed7a2c0-f772-11e5-88a0-ebdd94ead189.png">

<img width="310" alt="screenshot 2016-03-31 18 55 17" src="https://cloud.githubusercontent.com/assets/629266/14193367/21d537ee-f772-11e5-9454-90985471433a.png">

**Comment by fguillot** [comment]
Which version of the budget plugin do you have?

**Comment by iMiiTH** [comment]
I'm using 1.0.6. I just reinstalled the plugin as well, the issue is still there.

**Comment by oliviermaridat** [comment]
With the development version of Kanboard and Budget plugin, I have the same behaviour.

**Comment by oparoz** [comment]
```
PHP Fatal error:  Call to undefined method Kanboard\Core\Template::e() in /plugins/Budget/Template/budget/create.php on line 17
```

**Comment by oparoz** [comment]
PR is here: https://github.com/kanboard/plugin-budget/pull/13

**Comment by fguillot** [comment]
I merged your PR, thanks!
