### ISSUE TITLE
Internal Error: Controller or method not found for the given url!

### ISSUE THREAD

**Issue by middeke** [kanboard/plugin-budget#7]
Hi all,

I found an error in plugin budget.
Having more tasks than fitting on one page, the link to next page gives internal error in module "Cost breakdown"

The URL parameter "&plugin=budget" is missing.

URL page 1: kanboard/?controller=budget&action=breakdown&plugin=budget&project_id=1
URL page 2: kanboard/?controller=budget&action=breakdown&project_id=1&page=2&order=start&direction=DESC

**Comment by middeke** [comment]
Ok, I found a solution:

plugins/Budget/Controller/Budget.php
change line 41 from
            ->setUrl('budget', 'breakdown', array('project_id' => $project['id']))
to
            ->setUrl('budget', 'breakdown', array('plugin' => 'budget', 'project_id' => $project['id']))

**Comment by fguillot** [comment]
Thanks to report that, it's now fixed in master.
